<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/casbin.proto

namespace Xhtkyy\HyperfTools\Casbin\src\GrpcClient\GPBMetadata;

class Casbin
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
�
proto/casbin.protocasbin"
PoliciesReq
policies (	"\'
UserReq
user (	
domain (	"\'
RoleReq
role (	
domain (	"

UsersReply
user (	"

RolesReply
role (	"9
UserRoleReq
user (	
role (	
domain (	"
	BoolReply
result ("!
Permissions

permission (	"E
PermissionUserReq
user (	
domain (	

permission (	2�
Casbin6
getRolesForUser.casbin.UserReq.casbin.RolesReply6
getUsersForRole.casbin.RoleReq.casbin.UsersReply8
hasRoleForUser.casbin.UserRoleReq.casbin.BoolReply8
addRoleForUser.casbin.UserRoleReq.casbin.BoolReply;
deleteRoleForUser.casbin.UserRoleReq.casbin.BoolReply8
deleteRolesForUser.casbin.UserReq.casbin.BoolReply0

deleteUser.casbin.UserReq.casbin.BoolReply0

deleteRole.casbin.RoleReq.casbin.BoolReply:
deletePermission.casbin.Permissions.casbin.BoolReplyD
addPermissionForUser.casbin.PermissionUserReq.casbin.BoolReplyG
deletePermissionForUser.casbin.PermissionUserReq.casbin.BoolReply>
deletePermissionsForUser.casbin.UserReq.casbin.BoolReply=
getPermissionsForUser.casbin.UserReq.casbin.PermissionsD
hasPermissionForUser.casbin.PermissionUserReq.casbin.BoolReply>
getImplicitRolesForUser.casbin.UserReq.casbin.RolesReplyE
getImplicitPermissionsForUser.casbin.UserReq.casbin.PermissionsH
getImplicitUsersForPermission.casbin.Permissions.casbin.UsersReply>
getUsersForRoleInDomain.casbin.RoleReq.casbin.UsersReply>
getRolesForUserInDomain.casbin.UserReq.casbin.RolesReplyE
getPermissionsForUserInDomain.casbin.UserReq.casbin.Permissions@
addRoleForUserInDomain.casbin.UserRoleReq.casbin.BoolReplyC
deleteRoleForUserInDomain.casbin.UserRoleReq.casbin.BoolReply5
addPolicies.casbin.PoliciesReq.casbin.BoolReplyB,�App\\Grpc\\Casbin��App\\Grpc\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

