<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/Casbin/proto/casbin.proto

namespace Xhtkyy\HyperfTools\Casbin\src\GrpcClient;

/**
 * Protobuf type <code>casbin.Casbin</code>
 */
interface CasbinInterface
{
    /**
     * Method <code>getRolesForUser</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserReq $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\RolesReply
     */
    public function getRolesForUser(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserReq $request);

    /**
     * Method <code>getUsersForRole</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\RoleReq $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UsersReply
     */
    public function getUsersForRole(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\RoleReq $request);

    /**
     * Method <code>hasRoleForUser</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserRoleReq $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\BoolReply
     */
    public function hasRoleForUser(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserRoleReq $request);

    /**
     * Method <code>addRoleForUser</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserRoleReq $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\BoolReply
     */
    public function addRoleForUser(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserRoleReq $request);

    /**
     * Method <code>deleteRoleForUser</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserRoleReq $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\BoolReply
     */
    public function deleteRoleForUser(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserRoleReq $request);

    /**
     * Method <code>deleteRolesForUser</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserReq $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\BoolReply
     */
    public function deleteRolesForUser(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserReq $request);

    /**
     * Method <code>deleteUser</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserReq $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\BoolReply
     */
    public function deleteUser(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserReq $request);

    /**
     * Method <code>deleteRole</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\RoleReq $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\BoolReply
     */
    public function deleteRole(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\RoleReq $request);

    /**
     * Method <code>deletePermission</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\Permissions $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\BoolReply
     */
    public function deletePermission(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\Permissions $request);

    /**
     * Method <code>addPermissionForUser</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\PermissionUserReq $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\BoolReply
     */
    public function addPermissionForUser(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\PermissionUserReq $request);

    /**
     * Method <code>deletePermissionForUser</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\PermissionUserReq $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\BoolReply
     */
    public function deletePermissionForUser(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\PermissionUserReq $request);

    /**
     * Method <code>deletePermissionsForUser</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserReq $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\BoolReply
     */
    public function deletePermissionsForUser(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserReq $request);

    /**
     * Method <code>getPermissionsForUser</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserReq $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\Permissions
     */
    public function getPermissionsForUser(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserReq $request);

    /**
     * Method <code>hasPermissionForUser</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\PermissionUserReq $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\BoolReply
     */
    public function hasPermissionForUser(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\PermissionUserReq $request);

    /**
     * Method <code>getImplicitRolesForUser</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserReq $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\RolesReply
     */
    public function getImplicitRolesForUser(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserReq $request);

    /**
     * Method <code>getImplicitPermissionsForUser</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserReq $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\Permissions
     */
    public function getImplicitPermissionsForUser(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserReq $request);

    /**
     * Method <code>getImplicitUsersForPermission</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\Permissions $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UsersReply
     */
    public function getImplicitUsersForPermission(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\Permissions $request);

    /**
     * Method <code>getUsersForRoleInDomain</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\RoleReq $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UsersReply
     */
    public function getUsersForRoleInDomain(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\RoleReq $request);

    /**
     * Method <code>getRolesForUserInDomain</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserReq $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\RolesReply
     */
    public function getRolesForUserInDomain(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserReq $request);

    /**
     * Method <code>getPermissionsForUserInDomain</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserReq $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\Permissions
     */
    public function getPermissionsForUserInDomain(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserReq $request);

    /**
     * Method <code>addRoleForUserInDomain</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserRoleReq $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\BoolReply
     */
    public function addRoleForUserInDomain(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserRoleReq $request);

    /**
     * Method <code>deleteRoleForUserInDomain</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserRoleReq $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\BoolReply
     */
    public function deleteRoleForUserInDomain(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\UserRoleReq $request);

    /**
     * Method <code>addPolicies</code>
     *
     * @param \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\PoliciesReq $request
     * @return \Xhtkyy\HyperfTools\Casbin\src\GrpcClient\BoolReply
     */
    public function addPolicies(\Xhtkyy\HyperfTools\Casbin\src\GrpcClient\PoliciesReq $request);

}

