<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/health.proto

namespace Xhtkyy\HyperfTools\Grpc\Health;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc.health.v1.HealthCheckResponse</code>
 */
class HealthCheckResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.grpc.health.v1.ServingStatus status = 1;</code>
     */
    protected int $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $status
     * }
     */
    public function __construct($data = NULL) {
        Health::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.grpc.health.v1.ServingStatus status = 1;</code>
     * @return int
     */
    public function getStatus(): int {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.grpc.health.v1.ServingStatus status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus(int $var): static {
        GPBUtil::checkEnum($var, ServingStatus::class);
        $this->status = $var;

        return $this;
    }

}

