<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health.proto

namespace Xhtkyy\HyperfTools\Grpc\Health;

if (false) {
    /**
     * This class is deprecated. Use Xhtkyy\HyperfTools\Grpc\Health\HealthCheckResponse\ServingStatus instead.
     * @deprecated
     */
    class HealthCheckResponse_ServingStatus {}
}
class_exists(HealthCheckResponse\ServingStatus::class);
@trigger_error('Xhtkyy\HyperfTools\Grpc\Health\HealthCheckResponse_ServingStatus is deprecated and will be removed in the next major release. Use Xhtkyy\HyperfTools\Grpc\Health\HealthCheckResponse\ServingStatus instead', E_USER_DEPRECATED);

