<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/health.proto

namespace Xhtkyy\HyperfTools\Grpc\Health;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc.health.v1.HealthCheckRequest</code>
 */
class HealthCheckRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string service = 1;</code>
     */
    protected string $service = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $service
     * }
     */
    public function __construct($data = NULL) {
        Health::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string service = 1;</code>
     * @return string
     */
    public function getService(): string {
        return $this->service;
    }

    /**
     * Generated from protobuf field <code>string service = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setService(string $var): static {
        GPBUtil::checkString($var, True);
        $this->service = $var;

        return $this;
    }

}

