<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/reflection.proto

namespace Xhtkyy\HyperfTools\GrpcReflection\ServerReflection;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Serialized FileDescriptorProto messages sent by the server answering
 * a file_by_filename, file_containing_symbol, or file_containing_extension
 * request.
 *
 * Generated from protobuf message <code>grpc.reflection.v1alpha.FileDescriptorResponse</code>
 */
class FileDescriptorResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     *
     * Generated from protobuf field <code>repeated bytes file_descriptor_proto = 1;</code>
     */
    private $file_descriptor_proto;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $file_descriptor_proto
     *           Serialized FileDescriptorProto messages. We avoid taking a dependency on
     *           descriptor.proto, which uses proto2 only features, by making them opaque
     *           bytes instead.
     * }
     */
    public function __construct($data = NULL) {
        \Xhtkyy\HyperfTools\GrpcReflection\GPBMetadata\Reflection::initOnce();
        parent::__construct($data);
    }

    /**
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     *
     * Generated from protobuf field <code>repeated bytes file_descriptor_proto = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFileDescriptorProto()
    {
        return $this->file_descriptor_proto;
    }

    /**
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     *
     * Generated from protobuf field <code>repeated bytes file_descriptor_proto = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFileDescriptorProto($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->file_descriptor_proto = $arr;

        return $this;
    }

}

