<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc/reflection.proto

namespace Xhtkyy\HyperfTools\GrpcReflection\ServerReflection;

/**
 * Protobuf type <code>grpc.reflection.v1alpha.ServerReflection</code>
 */
interface ServerReflectionInterface
{
    /**
     * The reflection service is structured as a bidirectional stream, ensuring
     * all related requests go to a single server.
     *
     * Method <code>serverReflectionInfo</code>
     *
     * @param \Xhtkyy\HyperfTools\GrpcReflection\ServerReflection\ServerReflectionRequest $request
     * @return \Xhtkyy\HyperfTools\GrpcReflection\ServerReflection\ServerReflectionResponse
     */
    public function serverReflectionInfo(\Xhtkyy\HyperfTools\GrpcReflection\ServerReflection\ServerReflectionRequest $request);

}

